### PR TITLE
Fix unused variable warning emitted when using speedy(skip) (fixes #9)

### LINKED ISSUE #9: Using #[speedy(skip)] gives an unused variable warning
When I use `#[speedy(skip)]`, I get a compiler warning that there is an unused variable, even though I am using it. 

Example:
```
#[derive(Debug, Clone, Serialize, Deserialize, Writable, Readable)]
pub struct Test {
    #[speedy(skip)]
    pub monitors: Vec<(f64, usize, f64, bool)>,
}
```

```
warning: unused variable: `monitors`
  --> src/test.rs:40:9
   |
40 |     pub monitors: Vec<(f64, usize, f64, bool)>,
   |         ^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_monitors`
   ```

Adding `#[allow(dead_code)]` to the struct doesn't help.

### PR DESCRIPTION
**Pull request by vmalloc**

### CODE REVIEW

**Comment by koute** [comment]
Thanks!

**Comment by vmalloc** [comment]
@koute thank you for merging! Will it be possible to issue a patch release with this fix?

**Comment by koute** [comment]
I have a few unpushed commits queued locally, so I was planning to push them later today and release a `0.8.0`. (The version bump is due to a tiny breaking change with one method being renamed.) Would that be acceptable for you, or do you need a patch release?

**Comment by vmalloc** [comment]
That's perfectly fine by me. Thank you!

**Comment by koute** [comment]
Published.

**Comment by vmalloc** [comment]
@koute thanks!

**Pull request merged**
